name: Python Lint Code Scanning Action
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]
    steps:
      - uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: ruff
          python-version: ${{ matrix.python-version }}
